[pytest]
# Базовые настройки
addopts = -v -s --tb=long -rx --show-capture=all
python_files = test_*.py
testpaths = src/tests
filterwarnings = ignore::pytest.PytestUnhandledThreadExceptionWarning
markers =
    can: Тесты связи can